//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.27 at 10:06:48 AM CST 
//


package SFCProductionService;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for createSfc complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="createSfc"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SfcRequest" type="{http://production.ws.sapdev.com/}sfcProductionRequest" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "createSfc", propOrder = {
    "sfcRequest"
})
public class CreateSfc {

    @XmlElement(name = "SfcRequest")
    protected SfcProductionRequest sfcRequest;

    /**
     * Gets the value of the sfcRequest property.
     * 
     * @return
     *     possible object is
     *     {@link SfcProductionRequest }
     *     
     */
    public SfcProductionRequest getSfcRequest() {
        return sfcRequest;
    }

    /**
     * Sets the value of the sfcRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link SfcProductionRequest }
     *     
     */
    public void setSfcRequest(SfcProductionRequest value) {
        this.sfcRequest = value;
    }

}
