//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.27 at 10:06:48 AM CST 
//


package SFCProductionService;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the SFCProductionService package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SFCProductionException_QNAME = new QName("http://production.ws.sapdev.com/", "SFCProductionException");
    private final static QName _CreateSfc_QNAME = new QName("http://production.ws.sapdev.com/", "createSfc");
    private final static QName _CreateSfcResponse_QNAME = new QName("http://production.ws.sapdev.com/", "createSfcResponse");
    private final static QName _SfcProductionRequest_QNAME = new QName("http://production.ws.sapdev.com/", "sfcProductionRequest");
    private final static QName _SfcProductionResponse_QNAME = new QName("http://production.ws.sapdev.com/", "sfcProductionResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: SFCProductionService
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SFCProductionException }
     * 
     */
    public SFCProductionException createSFCProductionException() {
        return new SFCProductionException();
    }

    /**
     * Create an instance of {@link CreateSfc }
     * 
     */
    public CreateSfc createCreateSfc() {
        return new CreateSfc();
    }

    /**
     * Create an instance of {@link CreateSfcResponse }
     * 
     */
    public CreateSfcResponse createCreateSfcResponse() {
        return new CreateSfcResponse();
    }

    /**
     * Create an instance of {@link SfcProductionRequest }
     * 
     */
    public SfcProductionRequest createSfcProductionRequest() {
        return new SfcProductionRequest();
    }

    /**
     * Create an instance of {@link SfcProductionResponse }
     * 
     */
    public SfcProductionResponse createSfcProductionResponse() {
        return new SfcProductionResponse();
    }

    /**
     * Create an instance of {@link Throwable }
     * 
     */
    public Throwable createThrowable() {
        return new Throwable();
    }

    /**
     * Create an instance of {@link StackTraceElement }
     * 
     */
    public StackTraceElement createStackTraceElement() {
        return new StackTraceElement();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFCProductionException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://production.ws.sapdev.com/", name = "SFCProductionException")
    public JAXBElement<SFCProductionException> createSFCProductionException(SFCProductionException value) {
        return new JAXBElement<SFCProductionException>(_SFCProductionException_QNAME, SFCProductionException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateSfc }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://production.ws.sapdev.com/", name = "createSfc")
    public JAXBElement<CreateSfc> createCreateSfc(CreateSfc value) {
        return new JAXBElement<CreateSfc>(_CreateSfc_QNAME, CreateSfc.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateSfcResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://production.ws.sapdev.com/", name = "createSfcResponse")
    public JAXBElement<CreateSfcResponse> createCreateSfcResponse(CreateSfcResponse value) {
        return new JAXBElement<CreateSfcResponse>(_CreateSfcResponse_QNAME, CreateSfcResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SfcProductionRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://production.ws.sapdev.com/", name = "sfcProductionRequest")
    public JAXBElement<SfcProductionRequest> createSfcProductionRequest(SfcProductionRequest value) {
        return new JAXBElement<SfcProductionRequest>(_SfcProductionRequest_QNAME, SfcProductionRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SfcProductionResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://production.ws.sapdev.com/", name = "sfcProductionResponse")
    public JAXBElement<SfcProductionResponse> createSfcProductionResponse(SfcProductionResponse value) {
        return new JAXBElement<SfcProductionResponse>(_SfcProductionResponse_QNAME, SfcProductionResponse.class, null, value);
    }

}
